swagger: '2.0'
info:
  title: shurenyun API
  description: "数人云 API 文档"
  version: "1"
host: 192.168.59.104
schemes:
  - https
basePath: /api/v1
produces:
  - application/json
  
paths:
  /stacks:
    post:
      summary: 创建一个应用, 一个应用可包含多个服务
      description: 创建应用的API, 成功返回 HTTPStatus 200, 失败返回相应的错误信息
      tags:
        - Stacks
      parameters:
        - name: body
          in: body
          description: 创建应用所需的参数
          required: true
          schema:
            $ref: '#definitions/Bundle'
      response:
        '200':
          description: 创建成功返回success
          schema:
            $ref: '#definitions/GeneralOkResponse'
        '401':
          description: token 验证失败
          schema:
            $ref: '#definitions/GeneralErrorResponse'
        '400':
          description: 创建stack参数错误
          schema:
            $ref: '#definitions/GeneralErrorResponse'
        '503':
          description: 创建stack失败
          schema:
            $ref: '#definitions/GeneralErrorResponse'


  /login:
    post:
      summary: 通过用户邮箱和密码登陆系统, 登陆成功返回token
      description: 向服务器验证用户邮箱和密码, 验证成功返回当前登录用户的token; 否则返回相应的错误信息
      tags:
        - Account
      parameters:
        - name: body
          in: body
          description: 登陆用户的邮箱和密码
          required: true
          schema:
            type: object
            properties:
              Email:
                type: string
                description: 用户邮箱
              Password:
                type: string
                description: 用户密码
      responses:
        '200':
          description: 登陆成功返回当前用户的token
          schema:
            type: object
            required:
              - code
              - data
            properties:
              code:
                type: integer
                format: int32
              data:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: 用户登陆凭证
        '401':
          description: 登录失败, 返回相应的errorcode 和错误信息
          schema:
            $ref: '#definitions/GeneralErrorResponse'
                
    

definitions:
  GeneralOkResponse:
    type: object
    required:
      - code
      - data
    properties:
      code:
        type: integer
        format: int32
      data:
        type: string

  GeneralErrorResponse:
    type: object
    required:
      - code
      - data
      - message
    properties:
      code:
        type: integer
        format: int32
        description: 错误码，错误码对应详情可以查看(https://github.com/Dataman-Cloud/blackmamba/blob/master/src/constants.js)
      data:
        type: object
        description: 有关错误的详细信息, 如果没有返回{}
      message:
        type: string
        description: 错误的简单描述


  Bundle:
    type: object
    required:
      - Namespace
      - Stack
    properties:
      Namespace:
        type: string
        description: 应用的名称(应用所包含所有服务的前缀)
      Stack:
        schema:
          $ref: '#definitions/Stack'

  Stack:
    type: object
    required:
      - Version
      - Services
    properties:
      Version:
        type: string
        description: 应用版本
      Services:
        type: object
        description: 应用所包含的服务, 是一个key为服务名称value为服务参数的map
        additionalProperties:
          $ref: '#definitions/ServiceSpec'

  ServiceSpec:
    type: object
    description: 下发服务所需的静态参数
    required:
      - Name
      - Labels
      - TaskTemplate
      - Mode
      - UpdateConfig
      - Networks
      - EndpointSpec
    properties:
      Name:
        type: string
        description: 服务名称, 服务创建时会在服务名称前加上应用名称
      Labels:
        type: object
        description: 服务标签 类型 map[string]string
        additionalProperties:
          type: string
      TaskTemplate:
        schema:
          $ref: '#definitions/TaskSpec'
      Mode:
        schema:
          $ref: '#definitions/ServiceMode'
      UpdateConfig:
        schema:
          $ref: '#definitions/UpdateConfig'
      Networks:
        description: 服务需要加入的网络名称列表
        type: arrray
        items:
          description: 网络名称
          type: string
      EndpointSpec:
        schema:
          $ref: '#definitions/EndpointSpec'

  TaskSpec:
    description: 创建任务需要的静态参数
    type: object
    required:
      - ContainerSpec
      - Resources
      - RestartPolicy
      - Placement
      - LogDriver
    properties:
      ContainerSpec:
        scheam:
          $ref: '#definitions/ContainerSpec'
      Resources:
        scheam:
          $ref: '#definitions/Resources'
      RestartPolicy:
        scheam:
          $ref: '#definitions/RestartPolicy'
      Placement:
        scheam:
          $ref: '#definitions/Placement'
      LogDriver:
        scheam:
          $ref: '#definitions/LogDriver'

  ContainerSpec:
    description: 创建服务容器相关静态参数
    type: object
    required:
      - Image
      - Labels
      - Command
      - Args
      - Env
      - Dir
      - User
      - Groups
      - TTY
      - Mounts
      - StopGracePeriod
    properties:
      Image:
        description: 镜像名称
        type: string
      Labels:
        description: 容器标签
        type: object
        additionalProperties:
          type: string
      Command:
        description: 容器启动命令
        type: array
        items:
          type: string
      Args:
        description: 容器启动命令的参数
        type: array
        items:
          type: string
      Env:
        description: 容器启动时需要的环境变量
        type: array
        items:
          type: string
      Dir:
        description: 容器的工作目录
        type: string
      User:
        description: 容器所属用户
        type: string
      Groups:
        description: 容器所属用户组
        type: array
        items:
          type: string
      TTY:
        description: 是否分配虚拟终端
        type: bool
      Mounts:
        description: 容器挂载目录
        type: array
        items:
          $ref: '#definitions/Mount'
      StopGracePeriod:
        description: 杀死容器前的等待时间
        type: integer
        format: int32

  Mount:
    description: 挂载目录参数
    type: object
    required:
      - Type
      - Source
      - Target
      - ReadOnly
      - BindOptions
      - VolumeOptions
    properties:
      Type:
        description: 挂载类型 (bind/volume)
        type: string
      Source:
        description: 主机文件路径
        type: string
      Target:
        description: 容器文件路径
        type: string
      ReadOnly:
        description: 挂载到容器内部的文件是否只读
        type: bool
      BindOptions:
        description: 挂载方式为bind时的参数
        type: object
          scheam:
            description: 传播模式
            required:
              - Propagation
            properties:
              Propagation:
                description:

















































































































